{{- if .Values.schema.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "roboshop.fullname" . }}
  labels:
    {{- include "roboshop.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::086083061026:role/parameter-store-role-with-oidc
    "helm.sh/hook": pre-install
  {{- toYaml . | nindent 4 }}

spec:
  template:
    spec:
      volumes:
        - name: parameter-store
          emptyDir:
            sizeLimit: 5Mi
      initContainers:
        - name: parameters-pull
          image: 086083061026.dkr.ecr.us-east-1.amazonaws.com/parameter-pull
          imagePullPolicy: Always
          env:
            - name: ENV
              value: {{ .Values.ENV }}
            - name: COMPONENT
              value: {{ .Values.COMPONENT }}
      containers:
        - name: schema
          image: 086083061026.dkr.ecr.us-east-1.amazonaws.com/schema
          env:
            - name: SCHEMA_TYPE
              value: {{ .Values.schema.schema_type }}
            - name: COMPONENT
              value: {{ .Values.COMPONENT}}
          volumeMounts:
            - mountPath: /parameter-store
              name: parameter-store
      restartPolicy: Never
  backoffLimit: 1

{{- end }}
