{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "roboshop.serviceAccountName" . }}
  labels:
    {{- include "roboshop.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::086083061026:role/parameter-store-role-with-oidc
    "helm.sh/hook": pre-install
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
e